"""create initial schema

Revision ID: 1cdb074be8d4
Revises: 
Create Date: 2026-05-09 02:04:19.165726
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from sqlalchemy.dialects import postgresql

revision = '1cdb074be8d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('uploaded_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_checksum'), 'uploaded_files', ['checksum'], unique=False)
    op.create_index(op.f('ix_uploaded_files_user_id'), 'uploaded_files', ['user_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_file_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('detected_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_status'), 'datasets', ['status'], unique=False)
    op.create_index(op.f('ix_datasets_uploaded_file_id'), 'datasets', ['uploaded_file_id'], unique=False)
    op.create_index(op.f('ix_datasets_user_id'), 'datasets', ['user_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_dataset_id'), 'processing_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_user_id'), 'processing_jobs', ['user_id'], unique=False)
    op.create_table('ai_generated_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('summary_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('input_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generated_summaries_dataset_id'), 'ai_generated_summaries', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ai_generated_summaries_job_id'), 'ai_generated_summaries', ['job_id'], unique=False)
    op.create_table('analytics_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('numeric_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categorical_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('datetime_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_value_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outlier_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kpi_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trend_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('anomaly_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_results_dataset_id'), 'analytics_results', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_analytics_results_job_id'), 'analytics_results', ['job_id'], unique=False)
    op.create_table('forecast_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('datetime_column', sa.String(length=255), nullable=True),
    sa.Column('target_column', sa.String(length=255), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('forecast_horizon', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forecast_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_intervals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_results_dataset_id'), 'forecast_results', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_forecast_results_job_id'), 'forecast_results', ['job_id'], unique=False)
    op.create_table('chart_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('analytics_result_id', sa.UUID(), nullable=False),
    sa.Column('chart_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('x_column', sa.String(length=255), nullable=True),
    sa.Column('y_column', sa.String(length=255), nullable=True),
    sa.Column('group_by_column', sa.String(length=255), nullable=True),
    sa.Column('aggregation', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('chart_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analytics_result_id'], ['analytics_results.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_recommendations_analytics_result_id'), 'chart_recommendations', ['analytics_result_id'], unique=False)
    op.create_index(op.f('ix_chart_recommendations_dataset_id'), 'chart_recommendations', ['dataset_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('analytics_result_id', sa.UUID(), nullable=False),
    sa.Column('forecast_result_id', sa.UUID(), nullable=True),
    sa.Column('ai_summary_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_status', sa.String(length=50), nullable=False),
    sa.Column('report_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_summary_id'], ['ai_generated_summaries.id'], ),
    sa.ForeignKeyConstraint(['analytics_result_id'], ['analytics_results.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['forecast_result_id'], ['forecast_results.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_ai_summary_id'), 'reports', ['ai_summary_id'], unique=False)
    op.create_index(op.f('ix_reports_analytics_result_id'), 'reports', ['analytics_result_id'], unique=False)
    op.create_index(op.f('ix_reports_dataset_id'), 'reports', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_reports_forecast_result_id'), 'reports', ['forecast_result_id'], unique=False)
    op.create_index(op.f('ix_reports_report_status'), 'reports', ['report_status'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_forecast_result_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_dataset_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_analytics_result_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_ai_summary_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_chart_recommendations_dataset_id'), table_name='chart_recommendations')
    op.drop_index(op.f('ix_chart_recommendations_analytics_result_id'), table_name='chart_recommendations')
    op.drop_table('chart_recommendations')
    op.drop_index(op.f('ix_forecast_results_job_id'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_dataset_id'), table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_analytics_results_job_id'), table_name='analytics_results')
    op.drop_index(op.f('ix_analytics_results_dataset_id'), table_name='analytics_results')
    op.drop_table('analytics_results')
    op.drop_index(op.f('ix_ai_generated_summaries_job_id'), table_name='ai_generated_summaries')
    op.drop_index(op.f('ix_ai_generated_summaries_dataset_id'), table_name='ai_generated_summaries')
    op.drop_table('ai_generated_summaries')
    op.drop_index(op.f('ix_processing_jobs_user_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_dataset_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_datasets_user_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_uploaded_file_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_status'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_uploaded_files_user_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_checksum'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###